### ISSUE TITLE
anr 异常捕获问题

### ISSUE THREAD

**Issue by yuyifei** [cheyiliu/All-in-One#1]
看了您的wiki，其中提到了anr异常的处理，我现在比较疑惑的是我们怎么能够知道应用什么时候发生了anr异常，然后再去读取/data/anr/trace.txt文件呢？谢谢！

**Comment by cheyiliu** [comment]
当发生ANR时，系统是没有通知发送给app的。不过有另外的检测思路，见代码https://github.com/cheyiliu/ANR-WatchDog
